fusion_node:
  ros__parameters:
    # Time threshold for detection matching
    time_threshold: 0.5  # seconds

    # Distance threshold for detection matching
    distance_threshold: 1.0  # meters

    # Minimum distance to trust radar detections without fusion
    radar_trust_min: 2

    # Maximum distance to trust camera detections without fusion
    camera_trust_max: 12

    # Rotation matrix for transforming camera coordinates to radar coordinates
    rotation_matrix:  [0.97144628, -0.103039, 0.21371729,
                      -0.13169109, -0.9834477, 0.12445109,
                      0.19735646, -0.14904222, -0.96893593]

    # Translation vector for transforming camera coordinates to radar coordinates
    translation_vector: [0.1365367, 0.17875305, -0.17737524]

safety_monitor:
  ros__parameters:
  
    # Safety distances for target proximity
    safety_distance_1: 40  # meters
    safety_distance_2: 10  # meters
    safety_distance_3: 3   # meters

    # Speed overrides for safety distances
    speed_override_1: 5    # override speed for safety_distance_1 (m/s)
    speed_override_2: 2    # override speed for safety_distance_2 (m/s)
    speed_override_3: 0    # override speed for safety_distance_3 (stop)

    # Time reset values
    detection_active_reset_time: 5.0 # If nothing is detected for this time period, speed control is given to AgOpen
    vehicle_stopped_reset_time: 5.0 # If no detections are inside stop distance for this time period, speed control is given to AgOpen

radar_node:
  ros__parameters:
    # Can bus channel
    can_channel: can0

object_simulator:
  ros__parameters:
    # Min and max coordinate values for object simulator
    min_x: 0.0
    min_y: -10.0
    min_z: 0.0
    max_x: 50.0
    max_y: 10.0
    max_z: 0.0
