fusion_node:
  ros__parameters:
    # Time threshold for detection matching
    time_threshold: 0.5  # seconds

    # Distance threshold for detection matching
    distance_threshold: 1.0  # meters

    # Minimum distance to trust radar detections without fusion
    radar_trust_min: 5

    # Maximum distance to trust camera detections without fusion
    camera_trust_max: 12

    # Rotation matrix for transforming radar coordinates to camera coordinates
    rotation_matrix: [1.0, 0.0, 0.0,
                      0.0, 1.0, 0.0,
                      0.0, 0.0, 1.0]  # Default: identity matrix

    # Translation vector for transforming radar coordinates to camera coordinates
    translation_vector: [0.0, 0.0, 0.0]  # Default: no translation

safety_monitor:
  ros__parameters:
  
    # Safety distances for target proximity
    safety_distance_1: 40  # meters
    safety_distance_2: 10  # meters
    safety_distance_3: 3   # meters

    # Speed overrides for safety distances
    speed_override_1: 5    # override speed for safety_distance_1 (m/s)
    speed_override_2: 2    # override speed for safety_distance_2 (m/s)
    speed_override_3: 0    # override speed for safety_distance_3 (stop)

    # Time reset values
    detection_active_reset_time: 5.0 # If nothing is detected for this time period, speed control is given to AgOpen
    vehicle_stopped_reset_time: 5.0 # If no detections are inside stop distance for this time period, speed control is given to AgOpen

radar_node:
  ros__parameters:
    # Can bus channel
    can_channel: vcan0

object_simulator:
  ros__parameters:
    # Min and max coordinate values for object simulator
    min_x: 5.0
    min_y: -5.0
    min_z: 0.0
    max_x: 10.0
    max_y: 5.0
    max_z: 0.0
