name: ROS2 CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest  # This will use the latest Ubuntu (should be 24.04 soon)
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install ROS2 (Jazzy)
      run: |
        sudo apt update && sudo apt install -y curl gnupg lsb-release
        sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key | sudo apt-key add -
        echo "deb http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/ros2.list
        sudo apt update
        sudo apt install -y ros-jazzy-desktop python3-colcon-common-extensions python3-rosdep python3-rosinstall-generator python3-vcstool build-essential

    - name: Install Dependencies
      run: |
        sudo rosdep init || true
        rosdep update
        rosdep install --from-paths src --ignore-src -r -y

    - name: Build the Package
      run: |
        source /opt/ros/jazzy/setup.bash
        colcon build

    - name: Run Tests
      run: |
        source /opt/ros/jazzy/setup.bash
        colcon test --event-handlers console_cohesion+
        colcon test-result --verbose