name: ROS2 CI

on:
  push:
    branches:
      - main  # Runs tests on push to 'main'
  pull_request:
    branches:
      - main  # Runs tests on pull requests

jobs:
  test:
    runs-on: ubuntu-latest  # GitHub provides Ubuntu runners

    container:
      image: ros:jazzy  # Use the official ROS 2 Jazzy container

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Dependencies
      shell: bash
      run: |
        apt update
        rosdep update
        rosdep install --from-paths src --ignore-src -r -y

    - name: Build the Package
      shell: bash
      run: |
        source /opt/ros/jazzy/setup.bash
        colcon build --event-handlers console_direct+

    - name: Run Tests
      shell: bash
      run: |
        source /opt/ros/jazzy/setup.bash
        colcon test --event-handlers console_cohesion+
        colcon test-result --verbose
